version: '3.4'

services:
  my-dotnet-app:
    image: my-dotnet-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./src:/app/src
    networks:
      - my-network

networks:
  my-network:
    driver: bridge